### PR TITLE
Fix failing ref tests

### PR DESCRIPTION
**Pull request by chrisduerr**
Not sure why I was able to successfully complete the tests on my laptop, but they were clearly broken. This has been fixed by adding a serde default for `currently_enabled`.

Then the old ref test detection was also a bit broken, this now uses the serde default to test if it's an old ref test. So the default ScrollbackState is `enabled: false` and `currently_enabled: true`, which is an impossible state without loading the serde default. Then I just added a method to check for this state to detect if it's an old ref test.

Also because of the complications on my other machine, I recreated all the ref tests to make sure things are actually testing what I want to be testing.

### CODE REVIEW

**Comment by chrisduerr** [comment]
Do not merge this yet, I'm having some issues locally again.

**Comment by chrisduerr** [comment]
Should be good to go now! :+1:

**Comment by neon64** [comment]
It seems rather hacky to use an 'impossible state' to detect whether the test needs scrollback or not. Can't we just edit the `grid.json` files of the old tests to contain the correct information? ie: `"scrollback":{"enabled":false,"currently_enabled":false,"max_lines":whatever}`

**Comment by chrisduerr** [comment]
It's a lot of work because I'd need to manually set scrollback, visible_region_start and absolute_line_offset for every test. So I'm probably not gonna get around to it today.

**Comment by chrisduerr** [comment]
I have manually edited every old test and removed a bunch of code that was used to detect legacy tests. It should be nicer now.

The only code change I had to make was adding a `disable_scrollback` method to the config so I can setup the terminal of the test with the configuration of the grid.

Hope everything is okay now, tests should be green. :)

**Comment by neon64** [comment]
Thank you so much for all your effort @chrisduerr. I think the testing code is much cleaner now!

**Pull request merged**
