### PR TITLE
Fix most of the failing tests

### PR DESCRIPTION
**Pull request by tbodt**
The rest of the failing tests happen when the test case causes scrolling. Not sure how to modify Grid to fix those.

### CODE REVIEW

**Review by neon64 — COMMENTED** [review]
Is there a reasoning for why `index::AbsoluteLine` must be qualified? I don't really care either way but perhaps it's good to stay consistent?

**Comment by neon64** [comment]
Thanks very much for your help! I'll merge it so we can progress forward and think about the other tests (and also writing some new ones :D)

**Comment by tbodt** [comment]
No reason to qualify `index::AbsoluteLine`, but it's qualified in several other fields so why not be consistent.

**Comment by neon64** [comment]
Oh yeah true. I noticed though in the rest of the code I'd written in that file, I used unqualified `AbsoluteLine` and `Line` to save on typing. Perhaps I ought to ask @jwilm which style he prefers?

**Comment by jwilm** [comment]
I think it's probably safe to drop the qualified path for index types. Originally, I thought there was going to be a separate Column type, but that didn't end up being the case.

**Pull request merged**
